name: gee_metview
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.12
  - scipy==1.9.0
  - cython==0.29.32
  - yaml==0.2.5
  - PyYAML==6.0
  - requests==2.27.1
  - pandas==1.4.2
  - matplotlib-base==3.5.2
  - matplotlib-inline==0.1.2
  - earthengine-api==0.1.308
  - google-api-core==1.25.1
  - google-api-python-client==1.12.8
  - google-auth==1.35.0
  - google-auth-httplib2==0.1.0
  - google-cloud-core==1.7.1
  - google-cloud-storage==1.19.0
  - google-crc32c==1.1.2
  - google-resumable-media==2.1.0
  - googleapis-common-protos==1.56.1
  - numpy==1.22.4
  - geopandas==0.10.2
  - geopandas-base==0.10.2
  - pyproj==3.3.0
  - shapely==1.8.2
  - cdsapi==0.5.1
  - rioxarray==0.11.1
  - xarray==0.20.1
  - cftime==1.5.1.1
  - jupyter==1.0.0
  - dask-core==2022.5.0
  - cfgrib==0.9.10.1
  - pip==22.2.1
  - pip:
    - pymongo[gssapi,aws,ocsp,snappy,srv,tls,zstd,encryption]==4.2.0
  